### ISSUE TITLE
Option to disable shadows

### ISSUE THREAD

**Issue by warvariuc** [guari/eclipse-ui-theme#2]
Hi!
Thank you for a dark theme that works on Eclipse Kepler!
Can you please add an option or turn off by default shadows. This option is available in Chrome Theme, but it doesn't work when MoonRise theme is enabled. It's called there "Sash width" - "Thin Sash (Classic, No shadows)":
![snapshot1](https://f.cloud.github.com/assets/1035452/752214/6fabb51c-e53a-11e2-8b5f-f9c733fab84e.png)

Otherwise the shadows make too much distracting gradients:
![snapshot2](https://f.cloud.github.com/assets/1035452/752215/6fa6ae46-e53a-11e2-9da2-6e256ed6464b.png)

Thank you!

**Comment by guari** [comment]
Hi @warvariuc, to disable those shadows you can open _com.github.eclipseuitheme.moonrise_x.x.x.jar_  with an archive manager (eg. WinRar, 7Zip), then open with a text editor the file `\themes\css\moonrise-ui.css` and change those lines:

``` css
    ...
    .MPartStack {
        ...
        swt-shadow-visible: false;  /* modify this */
        ...
    }
    .MPartStack.active {
        ...
        swt-shadow-visible: false;  /* add this */
        ...
    }
    ...
```

if there'll be other users that prefer to do not have those shadows, then I will change it into the master branch.
