### ISSUE TITLE
MoonRise regression: now consumes the first click on various windows on linux

### ISSUE THREAD

**Issue by aloysbaillet** [guari/eclipse-ui-theme#44]
Hi,

I've been using MoonRise for a while now (and I would not use Eclipse without it, thanks!) but a recent update (a few weeks ago) introduced a regression when handling clicks on all windows except the editor: the first click on the window causes a refresh of the window and consumes the click event. This means that if the editor or another window is focused, I have to click twice in the project explorer in order to select a file (instead of a single time normally), and I need to click once, then double click to open the file.

I've been fairly thorough in my testing, including testing only Jeeeyul's theme but the bug only happens when either MoonRise(standalone) or MoonRise is selected.

I'm on linux x64 with gnome 2.28.2 and Eclipse Kepler SR1, and MoonRise was working perfectly fine before.
I've also completely re-installed my eclipse and tried in a blank workspace, and the issue came back.

It looks like the first click gives the focus to the window (the background color changes slightly) and consumes the click instead of letting the click event reach the actual widget and cause the selection to update.

Cheers,

Aloys

**Comment by marcelkottmann** [comment]
I am observing the same described behaviour. (Eclipse Luna with selected "Dark Theme" and Linux (Ubuntu, Gnome3)). This issue is very annoying and I'm close to switching back to the default theme.

**Comment by Kiiv** [comment]
Same here : Eclipse Kepler / Debian Stable / Gnome 3.4.2.
Very annoying, so I'm using Dark Juno instead at the moment... But Moonrise seems really better.

**Comment by antongrechko** [comment]
I have a workaround for this issue. There is probably a bug in .CSS. I doesn't familiar with CSS for SWT but I found that if you remove just one line (for _moonrise-ui.css_ lines # 430-438)

``` CSS
CTabFolder Tree, CTabFolder Canvas {
        background-color: #2F2F2F;
        color: #CCC;
    }
    .MPartStack.active Tree, /* remove this line */
    .MPartStack.active CTabFolder Canvas {
        background-color: #262626;
        color: #CCC;
    }
```

it'll solve doubleclick problem.
Hope this'll help.
