### ISSUE TITLE
How to change Vertical Ruler color?

### ISSUE THREAD

**Issue by lzrak47m4a1** [guari/eclipse-ui-theme#7]
I search it for a long time, but still can't solve it.

**Comment by guari** [comment]
Hi @lizherui,
what do you mean for 'Vertical Ruler'?
if you mean the vertical line between line numbers and code, you can catch it in CSS by doing something like this:

``` css
    #org-eclipse-e4-ui-compatibility-editor Composite > Canvas {
        background-color: #333;
    } 
```

You should use _CSS Spy_ to find the right widget without becoming crazy ;).
